#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace dasall::contracts {

// ---------------------------------------------------------------------------
// PromptComposeResult is the assembly-result object produced by PromptComposer,
// as defined by WP04-T004-D and ADR-006 §6.3.
//
// Main-flow chain position (WP04 Prompt chain):
//   ContextPacket -> PromptComposeRequest -> [PromptComposeResult]
//
// Core responsibility (ADR-006 §6.3):
//   PromptComposeResult carries only:
//     - provider-neutral messages / prompt payload
//     - selected Prompt identity and version metadata
//     - pruning metadata
//     - estimated token budget metadata
//     - composition warnings
//
// It is NOT:
//   - a ContextPacket write-back container
//   - a memory patch object
//   - a knowledge retrieval request/result
//   - a runtime execution result (Observation / AgentResult)
//
// Forbidden write-back semantics are governed by PromptBoundaryContracts.h
// (evaluate_compose_result_field_boundary), not by this data object itself.
// ---------------------------------------------------------------------------
struct PromptComposeResult {
  // -------------------------------------------------------------------------
  // Required fields (WP04-T004-D §2.1, 4 items)
  // -------------------------------------------------------------------------

  // Provider-neutral message payload generated by PromptComposer.
  // Represented as a normalized sequence of message fragments; provider-
  // specific serialization stays in downstream adapter layers.
  std::optional<std::vector<std::string>> messages;

  // Identifier of the PromptSpec selected for this composition pass.
  // Required for prompt governance, audit, and rollback traceability.
  std::optional<std::string> selected_prompt_id;

  // Selected PromptRelease version used for the rendered result.
  // Required so PromptPolicy and audit logs can trace the exact asset version.
  std::optional<std::string> selected_version;

  // Estimated token usage for the composed prompt payload.
  // Must be present and non-negative. Used by PromptPolicy / LLM routing.
  std::optional<std::int64_t> estimated_tokens;

  // -------------------------------------------------------------------------
  // Optional fields (WP04-T004-D §2.2, 2 items)
  // -------------------------------------------------------------------------

  // Sections removed during prompt composition due to budget or policy.
  // Present only when composition actually pruned one or more sections.
  std::optional<std::vector<std::string>> pruned_sections;

  // Warning signals emitted during composition, such as budget pressure,
  // fallback template use, or degraded prompt assembly.
  std::optional<std::vector<std::string>> composition_warnings;
};

}  // namespace dasall::contracts
