#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
BUILD_DIR="${BUILD_DIR:-${ROOT_DIR}/build-ci}"
GENERATOR="${CMAKE_GENERATOR:-Ninja}"
BUILD_TYPE="${CMAKE_BUILD_TYPE:-RelWithDebInfo}"
ENABLE_CPPCHECK="${DASALL_ENABLE_CPPCHECK:-OFF}"
ENABLE_CLANG_TIDY="${DASALL_ENABLE_CLANG_TIDY:-OFF}"

cmake -S "${ROOT_DIR}" -B "${BUILD_DIR}" \
  -G "${GENERATOR}" \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DDASALL_ENABLE_CPPCHECK="${ENABLE_CPPCHECK}" \
  -DDASALL_ENABLE_CLANG_TIDY="${ENABLE_CLANG_TIDY}"

cmake --build "${BUILD_DIR}" --parallel
